### ISSUE TITLE
Roadmap to collective.solr 7 (Plone 5.1 and Solr 7)

### ISSUE THREAD

**Issue by tisto** [collective/collective.solr#197]
We plan to do a collective.solr 7 release that supports Plone 5.1 and Solr 7. I will cut a new major release because I do not plan right now to support older Plone or Solr versions. This will be a huge refactoring and supporting multiple versions makes things a lot harder. 

If anybody is interested in older Plone or Solr versions please let me know asap. We might be able to work something out then...

Here is the roadmap:

- [x] Plone 5.1 compatibility
- [x] Solr 7 compatibility
- [x] Solr 7 recipe (kitconcept.recipe.solr)
- [ ] Fix unit test failures
  - 14 failures, 3 errors
- [x] Fix robot test failures
  - One test left that fails "Scenario As anonymous user I can filter the test results by creation date". I suspect this has something to do with the translation of the content-type title in Plone 5.1.
- [x] Travis setup that runs Solr 7 with Plone 5.1
- [x] Travis setup that runs Solr 7 with Plone 5.0
- [x] Travis setup that runs Solr 7 with Plone 4.3
- [x] Upload Robot reports to surge.sh
- [ ] Write docs and upgrade guide to Solr 7
- [x] defaultOperator is gone

Branch: "7.x"
Pull Request: https://github.com/collective/collective.solr/pull/198

**Comment by tisto** [comment]
The default operator is gone in Solr 7. So far this has been a parameter that the buildout recipe sets. I hard-coded the default operator to AND in c.solr for now. We could refactor this into a registry entry that can be set dynamically (in Solr 7 the defaultOperator is set for every search query, see https://issues.apache.org/jira/browse/SOLR-2724). Opinions @goschtl @gforcada @tomgross ?

**Comment by gforcada** [comment]
@tisto sorry to add more burden to you, but would you mind updating this issue checklist?

If I get it right, from the last merge requests, master compatibility matrix is:
- solr 7.4 and 7.5
- Plone 5.0.x

If we dropped compatibility with Plone 4.3.x and solr 4.x (the only that was supported on the latest released version), we should make a last minor release there stating that (I can volunteer on doing that).

Then the next steps should be:
- Plone 5.1 compatibility (collective.indexing got merged into CMFCore)
- Plone 5.2 compatibility (Zope 4)
- Python +3.6 compatibility
- trying to keep up with Solr releases :sweat_smile: 

Am I missing something? :thinking:

**Comment by csenger** [comment]
The boosting used in c.solr is not supported anymore. We either have to deprecate or reimplement the functionionality. https://lucene.apache.org/solr/guide/7_0/major-changes-in-solr-7.html#other-deprecations-and-removals:

> Index-time boosts have been removed from Lucene, and are no longer available from Solr. If any boosts are provided, they will be ignored by the indexing chain. As a replacement, index-time scoring factors should be indexed in a separate field and combined with the query score using a function query. See the section Function Queries for more information.

The skipped test for this is test_server:testReindexObjectKeepsExistingData()
