### ISSUE TITLE
New Documentation Structure

### ISSUE THREAD

**Issue by loechel** [collective/collective.solr#60]
As dicussed during [Plone Strategic Summit 2015](https://plone.org/roadmap/2015-strategic-summit-sorrento-summary) (Section: Enterprise Search and ZCatalog) Collective.solr should become more visibile and documentation should be included in [docs.plone.org](http://docs.plone.org/)

Therefore a move away from a monolitic README file to a Sphinx Documentation is necessary. 
I started a structuring of the documentation and created a branch [docs-restruturing](/collective/collective.solr/tree/docs-restructuring). 

**Todos:**
- [ ] Discuss what to include (collective.solr and setup of solr for Plone, maybe by including collective.recipe.solrinstance documentation in the docs) (at least @tisto, @saily, @reinhardt, @pilz, @loechel needed for discussion)
- [ ] Base Structure and Transfer of existing documentation in new Structure (started in branch [docs-restruturing](/collective/collective.solr/tree/docs-restructuring))
- [ ] Setup external for docs.plone.org to reference from in README's (@svx needed) 
- [ ] Merge of branch [docs-restruturing](/collective/collective.solr/tree/docs-restructuring) into [master](/collective/collective.solr/tree/master).

**Comment by gforcada** [comment]
:+1: !

**Comment by tisto** [comment]
+1

**Comment by loechel** [comment]
@tisto https://github.com/collective/collective.solr/pull/61 is ready for merge, so we have transfered documentation into new structure and everybody could and should write on the new documentation.

**Comment by tisto** [comment]
PR has been merged. No further action. Closing the issue. cc @loechel
